application:
  name: consumer

server:
  port: 8081

feign:
  client:
    config:
      commentClient:
        name: commentClient
        url: http://api-app-service:8080/api/books

spring:
  kafka:
    listener:
      type: batch # Обязательно для работы ConsumerRecords вместо ConsumerRecord
      ack-mode: MANUAL_IMMEDIATE # Коммитим вручную по завершении Future
      concurrency: 3 # Количество потоков-обработчиков пакетов
      error-handler: default-error-handler
    bootstrap-servers: localhost:9092
    consumer:
      group-id: comment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[max.poll.records]": 50
        "[fetch.max.wait.ms]": 5000
        "[fetch.min.bytes]": 1
        spring.json.use.type.headers: false # ВАЖНО! Отключает использование заголовков типов Кафки
        spring.deserialization.fail.on.unknown.properties: false # Игнорируем лишние поля
        spring.json.value.default.type: com.maslov.dto.CommentEvent
  cloud:
    loadbalancer:
      cache:
        ttl: 30
      enabled: true # Оставляем включенным, но даем ему подсказку
      clients:
        commentClient:
          addresses: http://localhost:${wiremock.server.port}/api/books

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    io.github.resilience4j: DEBUG # Полезно видеть состояния CB/Retry в логах
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.cloud.loadbalancer: TRACE

management:
  server:
    port: 8082 # <-- ВСЕ эндпоинты Actuator уйдут на внутренний порт 8082
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - prometheus
          - resilience4j
          - circuitbreakers
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  bulkhead:
    instances:
      commentApiBulkhead:
        max-concurrent-calls: 20
        max-wait-duration: 10ms

  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      commentApiBreaker: # Имя нашего выключателя
        registerHealthIndicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20 # Смотрим на последние 20 вызовов
        failure-rate-threshold: 50 # Если 50% неудач - открываем цепь
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 100
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 10s # Сколько секунд ждем перед попыткой Half-Open
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    retryAspectOrder: 2
    instances:
      commentApiRetry:
        max-attempts: 3            # Количество попыток
        wait-duration: 200ms      # Пауза между попытками (0,2 секунды)
        enable-exponential-backoff: true # ВКЛЮЧАЕТ работу мультипликатора (200ms -> 400ms -> 800ms)
        exponential-backoff-multiplier: 2.0 # Правильное имя параметра для множителя в Resilience4j
        randomized-wait-factor: 0.5 # Добавляет "дрожание" (jitter)
        retry-exceptions:
          - "feign.FeignException$InternalServerError" # 5xx
          - "feign.FeignException$BadGateway" # 502
          - "feign.FeignException$ServiceUnavailable" # 503
          - "feign.FeignException$GatewayTimeout" # 504
          - "java.net.ConnectException"
          - "java.net.SocketTimeoutException"
          - "org.springframework.web.client.ResourceAccessException"
          - "java.lang.RuntimeException"
        ignore-exceptions:
          - "feign.FeignException$NotFound" # 404
          - "feign.FeignException$Unauthorized" # 401
          - "feign.FeignException$BadRequest" # 400

  timelimiter:
    instances:
      commentApiLimiter:
        timeout-duration: 7s
        cancel-running-future: true
        time-limiter-strategy: SEMICOLON