application:
  name: consumer

services:
  books-maslov:
    url: localhost:8080
    path: /api/books

spring:
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: comment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.poll.records: 50
      fetch-max-wait-ms: 5000
      fetch-min-bytes: 1

server:
  port: 8081